### ISSUE TITLE
feat: Shizuku Integration for Android 11+

### ISSUE THREAD

**Issue by EliartBR** [Blocktopograph/Blocktopograph#1]
On Android 14, it is no longer possible to grant access to data/com.mojang.minecraftpe by opening the built-in files app with another app. At the moment, the only way I know of to access android/data is to use a file manager that uses shizuku to gain access.

Could you add a custom path as an alternative for this issue?
E.G: *main storage*/Blocktopograph or let users decide wich path.

**Comment by Etanarvazac** [comment]
> the only way II know of to access android/data is to use a file manager that uses shizuku

~~Even then, the `com.mojang.minecraftpe` folder doesn't display. I do have Shizuku and use X-Plore (which hooks into Shuzuku) and that folder is no longer readable.~~
Edit: I was finally able to get X-Plore to read MC's folder. So if Blocktopograph would hook into Shizuku as well and while that app is running, that may fix that. 
For NguyenDuck: You can find info for Shizuku here: https://github.com/RikkaApps/Shizuku

**Comment by AyleKalani** [comment]
> > the only way II know of to access android/data is to use a file manager that uses shizuku
> 
> Even then, the `com.mojang.minecraftpe` folder doesn't display. I do have Shizuku and use X-Plore (which hooks into Shuzuku) and that folder is no longer readable.

There is a method that I know of, which is using the Xposed module to allow access to Data/Obb again.

Module NoStorageRestrict: https://github.com/Xposed-Modules-Repo/com.github.dan.nostoragerestrict/releases

Unfortunately, it requires Root and LSPosed on the Device. (I don't recommend it for common users)

![Screenshot_20240325-190231](https://github.com/NguyenDuck/blocktopograph/assets/81342745/7d5f3c8b-10af-4156-8ec7-908309b82c76)

**Comment by Etanarvazac** [comment]
> Unfortunately, it requires Root and LSPosed on the Device. (I don't recommend it for common users)

@AyleKalani Shizuku doesn't require root and grants access to the `Android/data` directory. However, it does require using Android's USB/Wireless Debugging and the Android Debug Bridge (ADB).

**Comment by TukangM** [comment]
I sometimes don't use Shizuku... I prefer to use root. It might be better to integrate root permissions to access `com.mojang.minecraftpe` (if have root).

**Comment by Max-RM** [comment]
> I sometimes don't use Shizuku... I prefer to use root. It might be better to integrate root permissions to access `com.mojang.minecraftpe` (if have root).

I already asked him many times to add root mode

**Comment by TukangM** [comment]
@Max-RM huh weirdo... unless shizuku can run with root I guess

But I hate using shizuku one

**Comment by OmarKhamisBarakat** [comment]
Can someone explain how to use Shizuku (Explain like i am five) X-plore doesn’t seem to work with me in the choosing section

**Comment by EliartBR** [comment]
> Can someone explain how to use Shizuku (Explain like i am five) X-plore doesn’t seem to work with me in the choosing section

Try https://play.google.com/store/apps/details?id=com.folderv.file
X-plore wasn't working properly for me, so I installed FV and worked every time I needed it.

**Comment by OmarKhamisBarakat** [comment]
> > Can someone explain how to use Shizuku (Explain like i am five) X-plore doesn’t seem to work with me in the choosing section
> 
> Try https://play.google.com/store/apps/details?id=com.folderv.file
> X-plore wasn't working properly for me, so I installed FV and worked every time I needed it.

This is what i get when i am redirected to choose the folder, i have no choice to choose another app![Screenshot_20240409_035753_Files.jpg](https://github.com/NguyenDuck/blocktopograph/assets/151993600/77906011-6ec2-4757-a1cf-807907125797)

**Comment by EliartBR** [comment]
> This is what i get when i am redirected to choose the folder, i have no choice to choose another app
> 
> 

Currently this version of BlockTopograph does not have permission for Shizuku, you can use a file manager that has to copy your world from android/data and use this BlockTopograph https://github.com/oO0oO0oO0o0o00/blocktopograph/releases/tag/v1.9.4
To edit it.
![Screenshot_20240408_233528_Blocktopograph.png](https://github.com/NguyenDuck/blocktopograph/assets/134119462/bec6dcf0-1501-4b8b-a3d5-088df43e2ebe)

Just click on this folder icon in the upper right corner.

**Comment by Jonekadsen** [comment]
什么时候可以发布新的包呢

**Comment by Etanarvazac** [comment]
> When will the new package be released?

@Jonekadsen The original version was discontinued by Nguyen. Right now, there's a few active forks, but no deemed solution.
