### ISSUE TITLE
World not opening 

### ISSUE THREAD

**Issue by Badmaneers** [Blocktopograph/Blocktopograph#11]
I had built your project. For testing but when I launched the app it tooked like a minute to open and the worlds weren't even opening.

**Comment by Badmaneers** [comment]
![Screenshot_2024-07-19-16-47-00-04_c03321b9f1dce12c630f7b0686747f3a](https://github.com/user-attachments/assets/5bb5c374-5708-419b-b8c1-2004e19bafe8)

**Comment by THEGAMERPLAYSP** [comment]
Can you provide the apk you made ?

**Comment by Badmaneers** [comment]
> Can you provide the apk you made ?
Here,
[app-debug.zip](https://github.com/user-attachments/files/16694058/app-debug.zip)

**Comment by Badmaneers** [comment]
> Can you provide the apk you made ?

Adding the availability to use the application with root permission  will be nice.
So, the people that have a rooted phone doesn't have to deal with data folder restrictions.

**Comment by Max-RM** [comment]
> Adding the availability to use the application with root permission will be nice.
> So, the people that have a rooted phone doesn't have to deal with data folder restrictions.

[Check it.](https://github.com/Max-RM/1.20.0.21_MainActivity.smali_DIF)

But I want it to anyway.
