### ISSUE TITLE
feat: world scanner from games folder

### ISSUE THREAD

**Issue by NguyenDuck** [Blocktopograph/Blocktopograph#27]
- [x] scan games folder
- [x] put all scanned worlds to view holder
- [x] parse level.dat to view

**Comment by NguyenDuck** [comment]
![image](https://github.com/user-attachments/assets/f6df61f6-c615-4c42-9f3d-f2c27391e7a4)

**Comment by AyleKalani** [comment]
Version: 19Oct24
It is not getting Shizuku permission, only root permission is getting it. (No worlds view)

**Comment by NguyenDuck** [comment]
If you have root then its require su permission!

**Comment by AyleKalani** [comment]
https://github.com/user-attachments/assets/6efa25ca-5ca8-4cdc-bb50-c1d1e601b8a6



> If you have root then its require su permission!

Version: 20Oct24 - Do not enter the application in the new version, even after allowing root (Via Magisk) or allowing Shizuku
Version: 19Oct24 - This summer it was on the app, it just didn't show any world.
